import { Language } from './types';

export const TEXTS = {
  en: {
    welcome: "Elegant Options Reputation & SEO Growth Engine",
    selectLang: "Please select your preferred language",
    back: "Back",
    auditTitle: "AI Business Audit",
    inputs: {
      type: "Project Type",
      name: "Project Name",
      year: "Establishment / Branch Opening Year",
      reviews: "Current Review Count",
      customers: "Approx. how many customers per day?", 
      submit: "Run Deep Scan",
      mapPreview: "Live Location Detection",
      searching: "Locating...",
      locationConfirmed: "Location Verified",
      tapToConfirm: "Tap to confirm location",
      extracting: "Extracting public review data...",
      analysisComplete: "Analysis Complete",
      positive: "Positive",
      negative: "Negative",
      addressSim: "Detecting Address...",
      categories: {
        clinic: "Clinic / Medical",
        restaurant: "Restaurant",
        cafe: "Cafe",
        shop: "Retail / Shop",
        other: "Other"
      },
      placeholders: {
        clinic: "Clinic Name...",
        restaurant: "Restaurant Name...",
        cafe: "Cafe Name...",
        shop: "Shop Name...",
        other: "Business Name..."
      }
    },
    scanning: {
      connecting: "Connecting to Google Maps Database...",
      found: "Location Identified Successfully!",
      analyzing: "Analyzing Review Frequency...",
      velocity: "Calculating Growth Velocity (Last 30 Days)...",
      extractingStudy: "Extracting project case study...", // Added for the loading phase
      status: "Status: Active",
      match: "Data Matched.",
      weeklyLabel: "Reviews / Week",
      dailyLabel: "Reviews / Day",
      rankLabel: "SEO VISIBILITY STATUS"
    },
    dashboard: {
      title: "Performance & Revenue Analysis",
      age: "Market Presence",
      years: "Years",
      totalReviews: "Total Reviews",
      reviews: "Reviews",
      danger: "Strategic Impact Index",
      dangerText: "Current Pulse: You gain one review every",
      days: "days",
      weeklyRate: "Weekly Growth Rate",
      dailyRate: "Daily Growth Rate",
      monthlyRate: "Actual (Last 30 Days)",
      warningResult: "CRITICAL GAP: Your competitors are growing 10x faster because you rely on organic chance.",
      sentimentTitle: "Sentiment Analysis",
      posRatio: "Trust Score",
      negRatio: "Risk Score",
      rankTitle: "Google Maps Search Authority",
      rankDesc: "Google's algorithm prioritizes businesses with high engagement and frequent updates.",
      lossAnalysis: "Annual Revenue Opportunity",
      protectionAnalysis: "Annual Revenue Protection",
      lossDesc: "The profit you are missing by not appearing in the top 3.",
      protectionDesc: "The value our system protects by securing your #1 position.",
      revenueLogic: "Calculation logic: [Average Daily Traffic × 365 Days × 30% Market Leakage × Avg Ticket]. Businesses outside the Top 3 results lose ~30% of potential leads who prefer competitors with more social proof.",
      currency: "KWD",
      statusLabels: {
        invisible: "GHOST (INVISIBLE)",
        weak: "WEAK PRESENCE",
        average: "STABLE BUT LOW",
        strong: "MARKET LEADER",
        zero: "STAGNANT / ZERO GROWTH"
      },
      invisible: "NOT SUGGESTED TO CUSTOMERS",
      leader: "MARKET LEADER",
      ghost: "HIDDEN FROM SEARCH RESULTS",
      king: "DOMINATING THE MAP",
      velocityLabel: "Monthly Growth Velocity",
      annualProjection: "(Results after 1 year of using the system)",
      dailyVisitors: "Daily Visitors",
      expectedPulse: "Expected Daily Pulse (10%)",
      predictedAnnual: "Predicted Annual Growth",
      newReviews: "NEW 5-STAR REVIEWS",
      realPulse: "Current State (Actual Pulse)",
      highGrowth: "Dominance System (High Growth)",
    },
    report: {
      title: "The Strategic Fix: Dominate Local Search",
      impactTitle: "The 10% Conversion Logic",
      impactDesc: "Based on our AI benchmarks, 10% of visitors convert into 5-star reviews using our system. Here is your 1-year transformation:"
    },
    transformation: {
      title: "Decision Matrix: The Choice is Yours",
      desc: "Based on your actual performance vs. Elegant Options potential.",
      table: {
        col1: "Strategic Factor",
        col2: "Organic Path (Manual) 🐌",
        col3: "Elegant Options Path ⚡",
        row1: "Review Request Method",
        row1val1: "Passive / Manual",
        row1val2: "100% Automated WhatsApp",
        row2: "Reviews Per Year",
        row2val1: "Reviews/Year",
        row2val2: "Reviews/Year",
        row3: "SEO Rank Potential",
        row3val1: "Bottom Results",
        row3val2: "Top 3 Authority🥇",
        row4: "Customer Capture Rate",
        row4val1: "< 1% (Random)",
        row4val2: "10% Guaranteed Pulse",
      }
    },
    closing: {
      impact: "Reviews -> Better SEO -> More Traffic -> More Revenue 💰",
      stat: "Stat: 93% of customers read local reviews before deciding where to spend money.",
      ctaTitle: "Stop being invisible to your customers.",
      ctaDesc: "Scale your business today and activate the most powerful reputation management system in the market.",
      btn1: "✅ Activate via WhatsApp",
      btn2: "🔄 New Audit",
      btnVisual: "🎬 Visual Experience (Demo)",
      whatsappMessage: "Hello, I want to dominate Google Maps with Elegant Options.",
    },
    visualExp: {
      header: "Meta-Approved WhatsApp Simulation",
      status: "Official Business Account",
      online: "Online",
      messages: {
        clinic: "Hello! Thank you for visiting **{projectName}** today. We hope you had a comfortable visit. Could you spare 30 seconds to share your feedback?",
        restaurant: "Hello! Thank you for dining with us at **{projectName}** today. We hope you enjoyed your meal! Could you spare 30 seconds to share your feedback?",
        cafe: "Hello! Thank you for visiting **{projectName}** today. We hope you enjoyed your coffee! Could you spare 30 seconds to share your feedback?",
        shop: "Hello! Thank you for shopping at **{projectName}** today. We hope you found everything you needed. Could you spare 30 seconds to share your feedback?",
        other: "Hello! Thank you for visiting **{projectName}** today. We hope you enjoyed your experience. Could you spare 30 seconds to share your feedback?"
      },
      cta: "Tap to Rate Us ⭐⭐⭐⭐⭐",
      disclaimer: "This is a demonstration of how the automated request appears to your customers.",
      postDemoTitle: "Ready to Automate Your Growth?",
      postDemoDesc: "What you just experienced is the core of our reputation engine. We can implement this fully automated flow for your business to boost SEO and block negative public reviews.",
      postDemoBtn: "Chat with a Growth Expert"
    },
    survey: {
      title: "How was your experience?",
      subtitle: "We value your honest feedback to improve our services.",
      ratePrompt: "Please rate your visit at **{projectName}**",
      lowStarsTitle: "Reputation Shield Activated!",
      lowStarsDesc: "Because the rating is low, our system captures it as an **Internal Complaint**. It will NOT go to Google, saving your public reputation while allowing you to resolve the issue privately.",
      highStarsTitle: "Growth Engine Activated!",
      highStarsDesc: "For high ratings, the system encourages the customer to post on Google Maps instantly. This triggers the algorithm to boost your ranking and attract more customers.",
      placeholder: "Write your feedback here...",
      submitPrivate: "Send Private Complaint",
      submitGoogle: "Publish to Google Maps",
      thankYou: "Thank you for your feedback!",
      poweredBy: "POWERED BY ELEGANT OPTIONS"
    }
  },
  ar: {
    welcome: "محرك نمو السمعة وتحسين محركات البحث - Elegant Options",
    selectLang: "يرجى اختيار لغتك المفضلة لبدء تحليل مشروعك",
    back: "رجوع",
    auditTitle: "فحص المشروع الذكي",
    inputs: {
      type: "نوع المشروع",
      name: "اسم المشروع",
      year: "سنة التأسيس / افتتاح الفرع",
      reviews: "عدد التقييمات الحالي",
      customers: "كم عدد عملائك في اليوم تقريباً", 
      submit: "تشغيل الفحص العميق",
      mapPreview: "الكشف المباشر عن الموقع",
      searching: "جاري البحث...",
      locationConfirmed: "تم التحقق من الموقع",
      tapToConfirm: "إضغط لتأكيد الموقع",
      extracting: "جاري سحب بيانات التقييمات والعنوان...",
      analysisComplete: "اكتمل تحليل البيانات",
      positive: "إيجابي",
      negative: "سلبي",
      addressSim: "جاري تحديد العنوان...",
      categories: {
        clinic: "عيادة / طبي",
        restaurant: "مطعم",
        cafe: "كافيه",
        shop: "محل تجاري",
        other: "أخرى"
      },
      placeholders: {
        clinic: "اسم العيادة...",
        restaurant: "اسم المطعم...",
        cafe: "اسم الكافيه...",
        shop: "اسم المحل...",
        other: "اسم النشاط التجاري..."
      }
    },
    scanning: {
      connecting: "جارٍ الاتصال بقاعدة بيانات خرائط جوجل...",
      found: "تم تحديد الموقع وتأكيد العنوان!",
      analyzing: "تحليل وتيرة التقييمات...",
      velocity: "حساب سرعة النمو (آخر 30 يوم)...",
      extractingStudy: "جاري استخراج دراسة حالة المشروع...", // تم التحديث هنا
      status: "الحالة: نشط",
      match: "البيانات مطابقة.",
      weeklyLabel: "تقييم / أسبوع",
      dailyLabel: "تقييم / يوم",
      rankLabel: "حالة ظهور الـ SEO"
    },
    dashboard: {
      title: "تحليل الأداء المالي والنمو (Elegant Options)",
      age: "عمر النشاط في السوق",
      years: "سنوات",
      totalReviews: "إجمالي التقييمات",
      reviews: "تقييم",
      danger: "مؤشر التأثير الاستراتيجي للمشروع",
      dangerText: "بالنبض الحالي، يكتسب مشروعك تقييمًا واحدًا فقط كل",
      days: "أيام",
      weeklyRate: "معدل النمو الأسبوعي",
      dailyRate: "معدل النمو اليومي",
      monthlyRate: "تقييمات آخر 30 يوم (فعلي)",
      warningResult: "الفجوة: منافسوك يحاولون اللحاق بك، الاعتماد على الطلب اليدوي يهدد مركزك الأول.",
      sentimentTitle: "تحليل الانطباع العام",
      posRatio: "معدل الثقة",
      negRatio: "معدل المخاطرة",
      rankTitle: "سلطة البحث على خرائط جوجل",
      rankDesc: "خوارزمية جوجل تعطي الأولوية للأنشطة ذات التفاعل المستمر والتحديثات الأسبوعية.",
      lossAnalysis: "فرصة الإيرادات السنوية الضائعة",
      protectionAnalysis: "قيمة الإيرادات المحمية سنوياً",
      lossDesc: "الأرباح التي تفوتك بسبب عدم ظهورك في النتائج الثلاثة الأولى.",
      protectionDesc: "قيمة المبيعات التي يحميها نظامنا لضمان بقائك الرقم (1) دائماً.",
      revenueLogic: "يتم حساب هذا المبلغ بناءً على: [عدد عملائك في اليوم  × 365 يوم × 30% نسبة تسرب]. تشير الإحصائيات العالمية أن النشاط التجاري الذي لا يظهر في النتائج الثلاثة الأولى يفقد ما يصل إلى 30% من الزبائن المحتملين لصالح المنافسين ذوي التقييمات الأعلى. هذا الرقم يمثل القيمة المالية لتلك الفص الضائعة.",
      currency: "د.ك",
      statusLabels: {
        invisible: "شبح (غير مرئي للعملاء)",
        weak: "ظهور ضعيف جداً",
        average: "نشط لكن يحتاج دفع",
        strong: "مسيطر على السوق",
        zero: "توقف نمو (ركود)"
      },
      invisible: "مشروعك غير مقترح للعملاء حالياً",
      leader: "بطل السوق (LEADER)",
      ghost: "مخفي عن نتائج البحث (GHOST)",
      king: "مسيطر على الخريطة",
      velocityLabel: "سرعة النمو الشهري",
      annualProjection: "(نتائج استعمال النظام لمدة سنة واحدة)",
      dailyVisitors: "كم عدد عملائك في اليوم تقريباً",
      expectedPulse: "النبض اليومي المتوقع (10%)",
      predictedAnnual: "النمو السنوي المتوقع",
      newReviews: "تقييم 5 نجوم جديد",
      realPulse: "الوضع الحالي (النبض الحقيقي)",
      highGrowth: "نظام الهيمنة (نمو مرتفع)",
    },
    report: {
      title: "الحل الاستراتيجي: الهيمنة المطلقة على البحث",
      impactTitle: "منطق تحويل الـ 10%",
      impactDesc: "بناءً على مؤشراتنا الذكية، 10% من الزوار يتركون تقييماً إيجابياً عند تفعيل النظام. إليك تحولك السنوي المتوقع:"
    },
    transformation: {
      title: "مصفوفة القرار: الخيار لك",
      desc: "مقارنة بين مسار النمو الطبيعي (بناءً على الشهر الأخير) وبين قدرات Elegant Options الهائلة.",
      table: {
        col1: "العامل الاستراتيجي",
        col2: "المسار الطبيعي (يدوي) 🐌",
        col3: "مسار Elegant Options ⚡",
        row1: "طريقة طلب التقييم",
        row1val1: "سلبية / يدوية",
        row1val2: "أتمتة واتساب 100%",
        row2: "التقييمات السنوية",
        row2val1: "تقييم / سنة",
        row2val2: "تقييم / سنة",
        row3: "قوة تصدر الـ SEO",
        row3val1: "نتائج متأخرة",
        row3val2: "سلطة الـ 3 الأوائل🥇",
        row4: "معدل كسب العميل",
        row4val1: "أقل من 1% (عشوائي)",
        row4val2: "10% نبض مستمر",
      }
    },
    closing: {
      impact: "تقييمات أكثر -> SEO أقوى -> زوار أكثر -> أرباح أعلى 💰",
      stat: "حقيقة: 93% من العملاء يقرأون التقييمات المحلية قبل اتخاذ قرار الشراء.",
      ctaTitle: "توقف عن كونك غير مرئي لعملائك.",
      ctaDesc: "اتخذ القرار الاستراتيجي اليوم وحول زوارك إلى جيش من المروجين لمركزك الأول في جوجل.",
      btn1: "✅ تفعيل النظام عبر الواتساب",
      btn2: "🔄 فحص مشروع آخر",
      btnVisual: "🎬 تجربة مرئية (Demo)",
      whatsappMessage: "مرحباً، أرغب في حماية صدارتي على نتائج الخرائط مع نظام Elegant Options.",
    },
    visualExp: {
      header: "شاشة واتساب افتراضية معتمدة من Meta",
      status: "حساب أعمال رسمي (Official)",
      online: "نشط الآن",
      messages: {
        clinic: "مرحباً! شكراً لزيارتك لـ **{projectName}** اليوم. نتمنى أن تكون زيارتك مريحة. هل يمكنك تخصيص 30 ثانية لمشاركتنا رأيك؟",
        restaurant: "مرحباً! شكراً لزيارتك لـ **{projectName}** اليوم. نتمنى أن تكون استمتعت بوجبتك! هل يمكنك تخصيص 30 ثانية لمشاركتنا رأيك؟",
        cafe: "مرحباً! شكراً لزيارتك لـ **{projectName}** اليوم. نتمنى أن تكون استمتعت بقهوتك! هل يمكنك تخصيص 30 ثانية لمشاركتنا رأيك؟",
        shop: "مرحباً! شكراً لزيارتك لـ **{projectName}** اليوم. نتمنى أن تكون وجدت كل ما تبحث عنه. هل يمكنك تخصيص 30 ثانية لمشاركتنا رأيك؟",
        other: "مرحباً! شكراً لزيارتك لـ **{projectName}** اليوم. نتمنى أن تكون تجربتك كانت مميزة. هل يمكنك تخصيص 30 ثانية لمشاركتنا رأيك؟"
      },
      cta: "اضغط هنا لتقييمنا ⭐⭐⭐⭐⭐",
      disclaimer: "هذا العرض يوضح الطريقة التي تظهر بها رسائل طلب التقييم الأوتوماتيكية لعملائك.",
      postDemoTitle: "هل أنت جاهز لأتمتة نمو مشروعك؟",
      postDemoDesc: "ما رأيته الآن هو محركنا الذكي لزيادة التقييمات. يمكننا تفعيل هذا النظام المتكامل لمشروعك لضمان تصدر نتائج البحث وحماية سمعتك من التقييمات السلبية بشكل أوتوماتيكي بالكامل.",
      postDemoBtn: "تحدث مع خبير النمو الآن"
    },
    survey: {
      title: "كيف كانت تجربتك معنا؟",
      subtitle: "رأيك يهمنا لتطوير خدماتنا بشكل مستمر.",
      ratePrompt: "يرجى تقييم زيارتك لـ **{projectName}**",
      lowStarsTitle: "تفعيل درع حماية السمعة!",
      lowStarsDesc: "لأن التقييم منخفض، يقوم نظامنا بتحويله إلى **شكوى داخلية**. لن يظهر هذا التقييم في جوجل، مما يحمي سمعتك العامة ويسمح لك بمعالجة المشكلة بخصوصية.",
      highStarsTitle: "تفعيل محرك النمو الذكي!",
      highStarsDesc: "للتقييمات المرتفعة، يقوم النظام بتحفيز العميل لنشر رأيه في جوجل فوراً. هذا يرفع تصنيفك في الخرائط ويجذب عملاء جدد تلقائياً.",
      placeholder: "اكتب ملاحظاتك هنا...",
      submitPrivate: "إرسال شكوى داخلية",
      submitGoogle: "نشر على خرائط جوجل",
      thankYou: "شكراً لمشاركتنا رأيك!",
      poweredBy: "POWERED BY ELEGANT OPTIONS"
    }
  }
};
